name: MacMan
favicon: null
layout_spectrum: 0.99126
typography_spectrum: 0.7551749001722783
title: Apple Mac Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ceccc0'
    - '#f07931'
    - '#030506'
    - '#307298'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
