name: MacMan
favicon: null
layout_spectrum: 0.4372615348547697
typography_spectrum: 0.7551749001722783
title: Apple Mac Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6673334720544517
  lightness: 0.16560471872799098
  saturation: 0.28550132969394326
  rhythmicContrast: 0.7539902490098029
purpose: []
